### ISSUE TITLE
Create params for staker commission% and max commission

### ISSUE THREAD

**Issue by nitika-goel** [support-somish/NexusMutual#34]
Parameter for staker commission(20%) and max commission should be configurable by governance and the same should be used for methods like updateStakerCommissions()

**Comment by tech-somish** [comment]
1st part of your issue is correct but in 2nd part you are asking to make updateStakerCommissions() isGoverned.
but quotation contract is calling updateStakerCommissions(). if we make it isGoverned,quotation will not able to call it.
I think you are missunderstood purpose of updateStakerCommissions(). 
@nitika-goel

**Comment by tech-somish** [comment]
changes updated in git, check if any issue.
commit number :-- c4244ce984aa690e47c0f534df25454239c84759

**Comment by nitika-goel** [comment]
Changes have been made. Thanks.
